server:
  port: 8080

spring:
  application:
    name: dubbo-monitor
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dubbo_monitor?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: HKW520lxh..
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: HikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

dubbo:
  registry:
    address: zookeeper://10.9.22.26:2182?backup=10.9.22.27:2182,10.9.22.31:2182
  application:
    name: ${spring.application.name}
  local:
    host: localhost
    port: 31361

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lexin.dubbo.monitor.dao.domain
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
